- hosts: all
  tasks:
    - name: Normalize and set variables
      set_fact:
        repo_name_lower: "{{ repo_name | lower }}"
        image_name: "ghcr.io/{{ github_repository_owner | lower }}/{{ repo_name | lower }}"
        env_json: "{{ APP_ENV_JSON | from_json }}"
        ports:
          - { blue: "2020", green: "4040" }
          - { blue: "2021", green: "4041" }

    - name: Ensure config directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
        mode: '0755'

    - name: Log in to GHCR
      containers.podman.podman_login:
        registry: ghcr.io
        username: "{{ ghcr_user }}"
        password: "{{ ghcr_token }}"

    - name: Deploy application for each port mapping
      include_tasks: deploy.yml
      loop: "{{ ports }}"

    - name: Drop privileges & restrict user
      command: usermod --shell {{ obscured_dir }}/rbash.sh {{ ansible_user }}
      when: ansible_user != 'root'
      become: true
