name: Hash Password with Ansible

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password to hash'
        required: true
        default: 'MySecretPassword123'

jobs:
  hash_password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Hash password
        id: hash
        run: |
          HASHED=$(ansible localhost -m ansible.builtin.debug -a "msg={{ '$' + inputs.password | password_hash('sha512') }}" -c local)
          echo "hashed_password=$HASHED" >> $GITHUB_ENV

      - name: Show hashed password
        run: |
          echo "Hashed password: ${{ env.hashed_password }}"
