name: Verify pipx & ansible presence

on:
  workflow_dispatch:  # run manually

jobs:
  check-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Check pipx
        run: |
          echo "=== Checking pipx installation ==="
          if command -v pipx &> /dev/null; then
            echo "✅ pipx is installed"
            pipx --version
          else
            echo "❌ pipx is NOT installed"
          fi

      - name: Check ansible
        run: |
          echo "=== Checking ansible installation ==="
          if command -v ansible &> /dev/null; then
            echo "✅ ansible is installed"
            ansible --version
          else
            echo "❌ ansible is NOT installed"
          fi

          if command -v ansible-playbook &> /dev/null; then
            echo "✅ ansible-playbook is installed"
            ansible-playbook --version
          else
            echo "❌ ansible-playbook is NOT installed"
          fi

          if command -v ansible-galaxy &> /dev/null; then
            echo "✅ ansible-galaxy is installed"
            ansible-galaxy --version
          else
            echo "❌ ansible-galaxy is NOT installed"
          fi

          if command -v ansible-lint &> /dev/null; then
            echo "✅ ansible-lint is installed"
            ansible-lint --version
          else
            echo "❌ ansible-lint is NOT installed"
          fi

          if command -v ansible-vault &> /dev/null; then
            echo "✅ ansible-vault is installed"
            ansible-vault --version
          else
            echo "❌ ansible-vault is NOT installed"
          fi
