name: Hash Password with Ansible

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password to hash'
        required: true
        default: 'MySecretPassword123'

jobs:
  hash_password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          mypasswd=$(openssl passwd -6 'MyPlainTextPassword')
          echo $mypasswd

      - name: Hash password
        id: hash
        run: |
          set -euo pipefail

          PASSWORD="${{ github.event.inputs.password }}"
          
          # Run ansible to hash the password
          HASHED_OUTPUT=$(ansible localhost -m ansible.builtin.debug -a "msg={{ '$' + '${PASSWORD}' | password_hash('sha512') }}" -c local 2>&1) || {
            echo "Ansible failed! Output:"
            echo "$HASHED_OUTPUT"
            exit 1
          }

          # Extract the hashed password from ansible debug output
          HASHED=$(echo "$HASHED_OUTPUT" | grep -oP '(?<=\"msg\": \")[^\"]+')
          
          if [ -z "$HASHED" ]; then
            echo "Failed to extract hashed password!"
            echo "$HASHED_OUTPUT"
            exit 1
          fi

          echo "hashed_password=$HASHED" >> $GITHUB_ENV
          echo "Password hashed successfully."

      - name: Show hashed password
        run: |
          echo "Hashed password: ${{ env.hashed_password }}"
